### PR TITLE
Created recommendation for licenses.

### PR DESCRIPTION
**Pull request by martinheidegger**
We have been talking about licenses in https://github.com/nodeschool/discussions/issues/253 and this is the result as I understand it.

### CODE REVIEW

**Comment by maxogden** [comment]
we could also link to http://choosealicense.com/

**Comment by martinheidegger** [comment]
@maxogden and @Sequoia : I added your suggestions, thank you for them.

**Comment by kemitchell** [comment]
[Choose a License](http://choosealicense.com) comes complete with [a disclaimer](http://choosealicense.com/about/) and [related legal jazz](http://choosealicense.com/terms-of-service/) that make clear the choice of a license is nuanced and the site doesn't offer legal advice. Maybe NodeSchool can come together to advocate for a particular license or licenses as a community, but going into the weeds of license terms is a short path into minefields of law and license politics. It's awesome to see fellow coders really dive in and care about the license issues, but there just isn't coder-level clarity to be found in them.

Random thought: Maybe a visualization, based on npm metadata, of who uses what license would be more compelling? Just spit-balling, it might be fun to see clouds of Gravatars floating around in big MIT, Apache, and GPL clouds.

_You guessed it_: This post doesn't make me your lawyer or contain legal advice, which has to be tailored to your goals and situation. If you need legal advice, find an attorney!

**Comment by martinheidegger** [comment]
@kemitchell Go for the visualisation :+1: (Does it need mentioning in the markdown info?)

**Comment by kemitchell** [comment]
I will add to my projects list.

**Comment by martinheidegger** [comment]
Added some more sections ... I think it should be complete now.

**Comment by Sequoia** [comment]
My $0.02:
1. workshopper content package authors are **experienced OS devs who don't need a license recommendation**, they probably have their own opinions about licenses & are able to pick w/o assistance
2. OS software licensing is a very **contentious** issue & any sort of license recommendation *will* upset someone. There *is* a cost to introducing this topic into such a loosely federated project: it can turn people off or get their hackles up needlessly. The benefit gained from this cost, as I understand it, "consistent voice" or "consistency", vaguely defined, is scant & does not justify the cost imo.
3. OS software licensing is a very **complex** issue so a) it's a big scope to take on and b) we're unlikely to do justice. For example this PR says you can't earn money off an LGPL project-- afaik you *can* earn money by selling LGPL code as long as you redistribute the license & source. This is field of weeds its not worth wading into imo.

## Proposal
As @martinheidegger pointed out, GPL is not compatible with the MIT license on `workshopper`, so LGPL must be used if someone wants copyleft. This is great point & leads me to my proposal...
**List the licenses that are *compatible* with `workshopper`**

### example
Workshopper is released under the MIT license. The following licenses are suitable for lessons built on workshopper (i.e. compatible with the underlying MIT license):
* MIT *link*
* LGPL *link*
* BSD *link* etc.
For help choosing a license, check out http://choosealicense.com/

This way the package creators know what licenses are *compatible* & picking is left up to them. No recommendations, no value statements, no controversy, everybody's happy :tada: (maybe....?)

I sincerely hope nodeschool stays out of the OSS license controversy business... let's just encourage the building of free tools & let authors get licensing advice elsewhere :smile_cat:

**Comment by Sequoia** [comment]
At @martinheidegger's behest I started taking a whack at rewriting these guidelines (rather than just contributing criticisms! :smile_cat:), but upon investigation I've learned that:
1. The MIT does not prevent redistribution or derivative works from being released under *any* license, so long as the MIT license notice is preserved.  This means...
2. There is nothing preventing authors from releasing their workshoppers under GPL3 or any other license and...
3. **Every** license is compatible.

Given point 3, there's no need to enumerate "compatible" licenses as the list would read "1. every license." :yum: 

I also found that there's another repo in this namespace dedicated to providing information on creating new workshoppers: https://github.com/nodeschool/workshoppers

# Proposal
Add a to `nodeschool/workshoppers/readme.md`
> ## Licensing
> If you'd like to add a license to your lesson describing how other people can use it, check out http://choosealicense.com/

Sound good?

**Comment by scott-martinez** [comment]
Precisely, sequoia. If someone wanted to make (A)GPLed modifications to something under a lax pushover license that could be done with something like what's shown in section 2.2 over at http://softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html

**Comment by Sequoia** [comment]
Created a PR here: https://github.com/nodeschool/workshoppers/pull/30

**Comment by Sequoia** [comment]
https://github.com/nodeschool/workshoppers#licensing
:+1: Resolved

**Comment by finnp** [comment]
@Sequoia Awesome! So this PR can be closed right?

**Comment by Sequoia** [comment]
Yah. Good hustle! ⭐️

**Pull request closed without merging**
